insert into anomalies (id, purchase_id, status, description, solution) values (1, 1, 63, 'Unsp opn wnd unsp external genital organs, male, sequela', 85);
insert into anomalies (id, purchase_id, status, description, solution) values (2, 2, 80, 'Superficial thrombophlebitis in pregnancy, unsp trimester', 12);
insert into anomalies (id, purchase_id, status, description, solution) values (3, 3, 6, 'Other fracture of upper and lower end of left fibula', 59);
insert into anomalies (id, purchase_id, status, description, solution) values (4, 4, 75, 'Nondisp fx of distal phalanx of left little finger, sequela', 23);
insert into anomalies (id, purchase_id, status, description, solution) values (5, 5, 95, 'Labor and delivery complicated by short cord, unsp', 55);
insert into anomalies (id, purchase_id, status, description, solution) values (6, 6, 31, 'Idiopathic aseptic necrosis of right carpus', 30);
insert into anomalies (id, purchase_id, status, description, solution) values (7, 7, 64, 'Kidney transplant status', 51);
insert into anomalies (id, purchase_id, status, description, solution) values (8, 8, 59, 'Other secondary chronic gout, unsp hand, without tophus', 78);
insert into anomalies (id, purchase_id, status, description, solution) values (9, 9, 81, 'Nondisp fx of medial phalanx of right ring finger, sequela', 17);
insert into anomalies (id, purchase_id, status, description, solution) values (10, 10, 10, 'Inj flexor musc/fasc/tend and unsp finger at wrs/hnd lv', 3);
insert into anomalies (id, purchase_id, status, description, solution) values (11, 11, 59, 'Open bite of right index finger w/o damage to nail, subs', 80);
insert into anomalies (id, purchase_id, status, description, solution) values (12, 12, 62, 'Poisoning by butyrophen/thiothixen neuroleptc, acc, sequela', 16);
insert into anomalies (id, purchase_id, status, description, solution) values (13, 13, 45, 'Pressure ulcer of left buttock', 100);
insert into anomalies (id, purchase_id, status, description, solution) values (14, 14, 93, 'Deformity of reconstructed breast', 65);
insert into anomalies (id, purchase_id, status, description, solution) values (15, 15, 75, 'Unsp physl fx upper end r fibula, subs for fx w delay heal', 49);
insert into anomalies (id, purchase_id, status, description, solution) values (16, 16, 61, 'Corros second deg of head, face, and neck, unsp site, init', 60);
insert into anomalies (id, purchase_id, status, description, solution) values (17, 17, 97, 'Other specified diabetes mellitus with skin complications', 96);
insert into anomalies (id, purchase_id, status, description, solution) values (18, 18, 88, 'St Louis encephalitis', 67);
insert into anomalies (id, purchase_id, status, description, solution) values (19, 19, 85, 'Unspecified acquired deformity of unspecified limb', 34);
insert into anomalies (id, purchase_id, status, description, solution) values (20, 20, 90, 'Food in trachea causing asphyxiation, subsequent encounter', 88);
insert into anomalies (id, purchase_id, status, description, solution) values (21, 21, 93, 'Crushing injury of left knee', 64);
insert into anomalies (id, purchase_id, status, description, solution) values (22, 22, 74, 'Displ transverse fx r patella, 7thH', 82);
insert into anomalies (id, purchase_id, status, description, solution) values (23, 23, 41, 'Immersion hand, left hand, initial encounter', 50);
insert into anomalies (id, purchase_id, status, description, solution) values (24, 24, 6, 'Displ commnt fx shaft of rad, unsp arm, 7thM', 19);
insert into anomalies (id, purchase_id, status, description, solution) values (25, 25, 75, 'Oth fx upper end of left ulna, init for opn fx type 3A/B/C', 71);
insert into anomalies (id, purchase_id, status, description, solution) values (26, 26, 14, 'Displaced avulsion fracture of unspecified ilium', 2);
insert into anomalies (id, purchase_id, status, description, solution) values (27, 27, 78, 'Person outsd hv veh inj in clsn w pedl cyc in traf, sequela', 22);
insert into anomalies (id, purchase_id, status, description, solution) values (28, 28, 79, 'Pnctr w/o fb of left thumb w/o damage to nail, subs', 9);
insert into anomalies (id, purchase_id, status, description, solution) values (29, 29, 42, 'Collapsed vert, NEC, lumbar region, subs for fx w delay heal', 58);
insert into anomalies (id, purchase_id, status, description, solution) values (30, 30, 71, 'Nondisp transverse fx shaft of l ulna, 7thG', 95);
